add_catch(test_find_the_pivot_integer test.cpp)
