add_catch(test_find_the_duplicate_number test.cpp)
