add_catch(test_find_three_consecutive_integers_that_sum_to_a_given_number test.cpp)
