add_catch(test_a_number_after_a_double_reversal test.cpp)
